---
title: "conditional prob workshop"
format: html
editor: visual
---

```{r}
stroke <- read.csv('healthcare-dataset-stroke-data.csv')
library(tidyverse)
library(sf)
library(ggplot2)
```

```{r}
ggplot(data = stroke, aes(x=gender, fill = stroke)) +
  geom_bar()

ggplot(data = stroke, aes(x=factor(age), fill = stroke)) +
  geom_bar()

ggplot(data = stroke, aes(x=factors(stroke), fill = avg_glucose_level)) +
  geom_boxplot()
```

```{r}
hypertension <- stroke %>% 
  count(hypertension) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(hypertension == '1') %>% 
  pull(percent)
hypertension
```

```{r}

stroke_chance <- stroke %>% 
  count(stroke) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(stroke == '1') %>% 
  pull(percent)
stroke_chance
```

```{r}
HS_Chance <- stroke %>% 
  count(hypertension, stroke) %>% 
  group_by(stroke) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(stroke == 1, hypertension == 1) %>% 
  pull(percent)
HS_Chance
```

```{r}
(HS_Chance * stroke_chance) / 
hypertension
```
